name: Shizuku Testing
on:
  # membuat unittesting untuk mengecek dari pull
  pull_request:
    branches: [main, development]
  push:
    branches: [main, development]

  jobs:
    build:
      runs-on: ${{matrix.os}}
    startegy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      # check out kode dimana adalah git action
      # mengecek kode daripada project
      - name: checkout kode
        uses: actions/checkout@v4

      # memanggil environment dari python
      - name: setting python
        uses: actions/setup-python@v4

      # install requirement yang sudah disedikan dari project
      - name: install requirement
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r dev-requirements.txt

      # testing kode dengan pytest
      - name: testing kode dengan pytest
        run: |
          pytest testing/main_test.py --verbose
